### PR TITLE
GitHub Action to lint Python code

### LINKED ISSUE #27: Setup CI
piggyback on the configuration here by @cclauss https://github.com/internetarchive/wcdimportbot/blob/main/.github/workflows/lint_python.yml

### PR DESCRIPTION
**Pull request by cclauss**
Closes #27
Test results: https://github.com/cclauss/asseeibot/actions

### CODE REVIEW

**Comment by dpriskorn** [comment]
Thanks!

**Comment by cclauss** [comment]
Plenty of `|| true` to remove ;-)

**Comment by dpriskorn** [comment]
> Plenty of `|| true` to remove ;-)

I failed to understand this comment.

**Comment by cclauss** [comment]
Try to remove `|| true` from each of the lines that end with that while keeping the tests green.

**Pull request merged**
